-- AI Assistance Disclosure: OpenAI Codex (GPT-6), 2026-09-25. Generated by Drizzle from the reviewed Supplier schema corrections; author review required before submission.
ALTER TABLE "suppliers" ALTER COLUMN "latitude" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "suppliers" ALTER COLUMN "longitude" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "suppliers" ADD CONSTRAINT "suppliers_building_code_allowed" CHECK ("suppliers"."building_code" in ('COM2', 'COM3', 'CENTRAL_LIBRARY', 'ENG_E3', 'ENG_E4', 'ENG_EA', 'FRONTIER', 'TERRACE', 'THE_RIDGE', 'YIH', 'PGP', 'HSSML', 'MED_SCI_LIBRARY', 'AS8', 'INNOVATION_4_0'));
